export enum Design {
  None = '',
  AndorraTelecom = 'andorratelecom',
  Gmail = 'gmail',
  GovernAndorra = 'govern-andorra',
  Horde = 'horde',
  Linkedin = 'linkedin',
  Outlook = 'outlook',
  OutlookOld = 'outlook-old',
  Proton = 'proton',
  Telegram = 'telegram',
  WhatsApp = 'whatsapp',
  Yahoo = 'yahoo',
  Yandex = 'yandex',
  iCloud = 'icloud',
  Zoho = 'zoho',
}
